#!/usr/bin/env bun
// @generated by mcporter@0.7.3 on 2026-01-30T21:37:37.831Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "chrome-devtools",
  "description": "Chrome DevTools MCP server",
  "command": {
    "kind": "stdio",
    "command": "npx",
    "args": [
      "-y",
      "chrome-devtools-mcp@latest"
    ],
    "cwd": "/Users/tim/.openclaw/workspace/config"
  },
  "source": {
    "kind": "local",
    "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
    }
  ],
  "lifecycle": {
    "mode": "keep-alive"
  }
} as const;
const embeddedSchemas = {
  "click": {
    "type": "object",
    "properties": {
      "uid": {
        "type": "string",
        "description": "The uid of an element on the page from the page content snapshot"
      },
      "dblClick": {
        "type": "boolean",
        "description": "Set to true for double clicks. Default is false."
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "uid"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "close_page": {
    "type": "object",
    "properties": {
      "pageId": {
        "type": "number",
        "description": "The ID of the page to close. Call list_pages to list pages."
      }
    },
    "required": [
      "pageId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "drag": {
    "type": "object",
    "properties": {
      "from_uid": {
        "type": "string",
        "description": "The uid of the element to drag"
      },
      "to_uid": {
        "type": "string",
        "description": "The uid of the element to drop into"
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "from_uid",
      "to_uid"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "emulate": {
    "type": "object",
    "properties": {
      "networkConditions": {
        "type": "string",
        "enum": [
          "No emulation",
          "Offline",
          "Slow 3G",
          "Fast 3G",
          "Slow 4G",
          "Fast 4G"
        ],
        "description": "Throttle network. Set to \"No emulation\" to disable. If omitted, conditions remain unchanged."
      },
      "cpuThrottlingRate": {
        "type": "number",
        "minimum": 1,
        "maximum": 20,
        "description": "Represents the CPU slowdown factor. Set the rate to 1 to disable throttling. If omitted, throttling remains unchanged."
      },
      "geolocation": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "latitude": {
                "type": "number",
                "minimum": -90,
                "maximum": 90,
                "description": "Latitude between -90 and 90."
              },
              "longitude": {
                "type": "number",
                "minimum": -180,
                "maximum": 180,
                "description": "Longitude between -180 and 180."
              }
            },
            "required": [
              "latitude",
              "longitude"
            ],
            "additionalProperties": false
          },
          {
            "type": "null"
          }
        ],
        "description": "Geolocation to emulate. Set to null to clear the geolocation override."
      },
      "userAgent": {
        "type": [
          "string",
          "null"
        ],
        "description": "User agent to emulate. Set to null to clear the user agent override."
      },
      "colorScheme": {
        "type": "string",
        "enum": [
          "dark",
          "light",
          "auto"
        ],
        "description": "Emulate the dark or the light mode. Set to \"auto\" to reset to the default."
      },
      "viewport": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "width": {
                "type": "integer",
                "minimum": 0,
                "description": "Page width in pixels."
              },
              "height": {
                "type": "integer",
                "minimum": 0,
                "description": "Page height in pixels."
              },
              "deviceScaleFactor": {
                "type": "number",
                "minimum": 0,
                "description": "Specify device scale factor (can be thought of as dpr)."
              },
              "isMobile": {
                "type": "boolean",
                "description": "Whether the meta viewport tag is taken into account. Defaults to false."
              },
              "hasTouch": {
                "type": "boolean",
                "description": "Specifies if viewport supports touch events. This should be set to true for mobile devices."
              },
              "isLandscape": {
                "type": "boolean",
                "description": "Specifies if viewport is in landscape mode. Defaults to false."
              }
            },
            "required": [
              "width",
              "height"
            ],
            "additionalProperties": false
          },
          {
            "type": "null"
          }
        ],
        "description": "Viewport to emulate. Set to null to reset to the default viewport."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "evaluate_script": {
    "type": "object",
    "properties": {
      "function": {
        "type": "string",
        "description": "A JavaScript function declaration to be executed by the tool in the currently selected page.\nExample without arguments: `() => {\n  return document.title\n}` or `async () => {\n  return await fetch(\"example.com\")\n}`.\nExample with arguments: `(el) => {\n  return el.innerText;\n}`\n"
      },
      "args": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "uid": {
              "type": "string",
              "description": "The uid of an element on the page from the page content snapshot"
            }
          },
          "required": [
            "uid"
          ],
          "additionalProperties": false
        },
        "description": "An optional list of arguments to pass to the function."
      }
    },
    "required": [
      "function"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "fill": {
    "type": "object",
    "properties": {
      "uid": {
        "type": "string",
        "description": "The uid of an element on the page from the page content snapshot"
      },
      "value": {
        "type": "string",
        "description": "The value to fill in"
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "uid",
      "value"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "fill_form": {
    "type": "object",
    "properties": {
      "elements": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "uid": {
              "type": "string",
              "description": "The uid of the element to fill out"
            },
            "value": {
              "type": "string",
              "description": "Value for the element"
            }
          },
          "required": [
            "uid",
            "value"
          ],
          "additionalProperties": false
        },
        "description": "Elements from snapshot to fill out."
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "elements"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get_console_message": {
    "type": "object",
    "properties": {
      "msgid": {
        "type": "number",
        "description": "The msgid of a console message on the page from the listed console messages"
      }
    },
    "required": [
      "msgid"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "get_network_request": {
    "type": "object",
    "properties": {
      "reqid": {
        "type": "number",
        "description": "The reqid of the network request. If omitted returns the currently selected request in the DevTools Network panel."
      },
      "requestFilePath": {
        "type": "string",
        "description": "The absolute or relative path to save the request body to. If omitted, the body is returned inline."
      },
      "responseFilePath": {
        "type": "string",
        "description": "The absolute or relative path to save the response body to. If omitted, the body is returned inline."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "handle_dialog": {
    "type": "object",
    "properties": {
      "action": {
        "type": "string",
        "enum": [
          "accept",
          "dismiss"
        ],
        "description": "Whether to dismiss or accept the dialog"
      },
      "promptText": {
        "type": "string",
        "description": "Optional prompt text to enter into the dialog."
      }
    },
    "required": [
      "action"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "hover": {
    "type": "object",
    "properties": {
      "uid": {
        "type": "string",
        "description": "The uid of an element on the page from the page content snapshot"
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "uid"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "list_console_messages": {
    "type": "object",
    "properties": {
      "pageSize": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "description": "Maximum number of messages to return. When omitted, returns all requests."
      },
      "pageIdx": {
        "type": "integer",
        "minimum": 0,
        "description": "Page number to return (0-based). When omitted, returns the first page."
      },
      "types": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "log",
            "debug",
            "info",
            "error",
            "warn",
            "dir",
            "dirxml",
            "table",
            "trace",
            "clear",
            "startGroup",
            "startGroupCollapsed",
            "endGroup",
            "assert",
            "profile",
            "profileEnd",
            "count",
            "timeEnd",
            "verbose",
            "issue"
          ]
        },
        "description": "Filter messages to only return messages of the specified resource types. When omitted or empty, returns all messages."
      },
      "includePreservedMessages": {
        "type": "boolean",
        "default": false,
        "description": "Set to true to return the preserved messages over the last 3 navigations."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "list_network_requests": {
    "type": "object",
    "properties": {
      "pageSize": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "description": "Maximum number of requests to return. When omitted, returns all requests."
      },
      "pageIdx": {
        "type": "integer",
        "minimum": 0,
        "description": "Page number to return (0-based). When omitted, returns the first page."
      },
      "resourceTypes": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "document",
            "stylesheet",
            "image",
            "media",
            "font",
            "script",
            "texttrack",
            "xhr",
            "fetch",
            "prefetch",
            "eventsource",
            "websocket",
            "manifest",
            "signedexchange",
            "ping",
            "cspviolationreport",
            "preflight",
            "fedcm",
            "other"
          ]
        },
        "description": "Filter requests to only return requests of the specified resource types. When omitted or empty, returns all requests."
      },
      "includePreservedRequests": {
        "type": "boolean",
        "default": false,
        "description": "Set to true to return the preserved requests over the last 3 navigations."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "list_pages": {
    "type": "object",
    "properties": {},
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "navigate_page": {
    "type": "object",
    "properties": {
      "type": {
        "type": "string",
        "enum": [
          "url",
          "back",
          "forward",
          "reload"
        ],
        "description": "Navigate the page by URL, back or forward in history, or reload."
      },
      "url": {
        "type": "string",
        "description": "Target URL (only type=url)"
      },
      "ignoreCache": {
        "type": "boolean",
        "description": "Whether to ignore cache on reload."
      },
      "handleBeforeUnload": {
        "type": "string",
        "enum": [
          "accept",
          "decline"
        ],
        "description": "Whether to auto accept or beforeunload dialogs triggered by this navigation. Default is accept."
      },
      "initScript": {
        "type": "string",
        "description": "A JavaScript script to be executed on each new document before any other scripts for the next navigation."
      },
      "timeout": {
        "type": "integer",
        "description": "Maximum wait time in milliseconds. If set to 0, the default timeout will be used."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "new_page": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string",
        "description": "URL to load in a new page."
      },
      "background": {
        "type": "boolean",
        "description": "Whether to open the page in the background without bringing it to the front. Default is false (foreground)."
      },
      "timeout": {
        "type": "integer",
        "description": "Maximum wait time in milliseconds. If set to 0, the default timeout will be used."
      }
    },
    "required": [
      "url"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "performance_analyze_insight": {
    "type": "object",
    "properties": {
      "insightSetId": {
        "type": "string",
        "description": "The id for the specific insight set. Only use the ids given in the \"Available insight sets\" list."
      },
      "insightName": {
        "type": "string",
        "description": "The name of the Insight you want more information on. For example: \"DocumentLatency\" or \"LCPBreakdown\""
      }
    },
    "required": [
      "insightSetId",
      "insightName"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "performance_start_trace": {
    "type": "object",
    "properties": {
      "reload": {
        "type": "boolean",
        "description": "Determines if, once tracing has started, the current selected page should be automatically reloaded. Navigate the page to the right URL using the navigate_page tool BEFORE starting the trace if reload or autoStop is set to true."
      },
      "autoStop": {
        "type": "boolean",
        "description": "Determines if the trace recording should be automatically stopped."
      },
      "filePath": {
        "type": "string",
        "description": "The absolute file path, or a file path relative to the current working directory, to save the raw trace data. For example, trace.json.gz (compressed) or trace.json (uncompressed)."
      }
    },
    "required": [
      "reload",
      "autoStop"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "performance_stop_trace": {
    "type": "object",
    "properties": {
      "filePath": {
        "type": "string",
        "description": "The absolute file path, or a file path relative to the current working directory, to save the raw trace data. For example, trace.json.gz (compressed) or trace.json (uncompressed)."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "press_key": {
    "type": "object",
    "properties": {
      "key": {
        "type": "string",
        "description": "A key or a combination (e.g., \"Enter\", \"Control+A\", \"Control++\", \"Control+Shift+R\"). Modifiers: Control, Shift, Alt, Meta"
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "key"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "resize_page": {
    "type": "object",
    "properties": {
      "width": {
        "type": "number",
        "description": "Page width"
      },
      "height": {
        "type": "number",
        "description": "Page height"
      }
    },
    "required": [
      "width",
      "height"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "select_page": {
    "type": "object",
    "properties": {
      "pageId": {
        "type": "number",
        "description": "The ID of the page to select. Call list_pages to get available pages."
      },
      "bringToFront": {
        "type": "boolean",
        "description": "Whether to focus the page and bring it to the top."
      }
    },
    "required": [
      "pageId"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "take_screenshot": {
    "type": "object",
    "properties": {
      "format": {
        "type": "string",
        "enum": [
          "png",
          "jpeg",
          "webp"
        ],
        "default": "png",
        "description": "Type of format to save the screenshot as. Default is \"png\""
      },
      "quality": {
        "type": "number",
        "minimum": 0,
        "maximum": 100,
        "description": "Compression quality for JPEG and WebP formats (0-100). Higher values mean better quality but larger file sizes. Ignored for PNG format."
      },
      "uid": {
        "type": "string",
        "description": "The uid of an element on the page from the page content snapshot. If omitted takes a pages screenshot."
      },
      "fullPage": {
        "type": "boolean",
        "description": "If set to true takes a screenshot of the full page instead of the currently visible viewport. Incompatible with uid."
      },
      "filePath": {
        "type": "string",
        "description": "The absolute path, or a path relative to the current working directory, to save the screenshot to instead of attaching it to the response."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "take_snapshot": {
    "type": "object",
    "properties": {
      "verbose": {
        "type": "boolean",
        "description": "Whether to include all possible information available in the full a11y tree. Default is false."
      },
      "filePath": {
        "type": "string",
        "description": "The absolute path, or a path relative to the current working directory, to save the snapshot to instead of attaching it to the response."
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "upload_file": {
    "type": "object",
    "properties": {
      "uid": {
        "type": "string",
        "description": "The uid of the file input element or an element that will open file chooser on the page from the page content snapshot"
      },
      "filePath": {
        "type": "string",
        "description": "The local path of the file to upload"
      },
      "includeSnapshot": {
        "type": "boolean",
        "description": "Whether to include a snapshot in the response. Default is false."
      }
    },
    "required": [
      "uid",
      "filePath"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "wait_for": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "Text to appear on the page"
      },
      "timeout": {
        "type": "integer",
        "description": "Maximum wait time in milliseconds. If set to 0, the default timeout will be used."
      }
    },
    "required": [
      "text"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
} as const;
const embeddedName = "chrome-devtools";
const embeddedDescription = "Chrome DevTools MCP server";
const generatorInfo = "Generated by mcporter@0.7.3 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "click",
    "description": "Clicks on the provided element",
    "usage": "click --uid <uid> [--dbl-click <dbl-click:true|false>] [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--uid <uid> [--dbl-click <dbl-click:true|false>] [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "close-page",
    "description": "Closes the page by its index. The last open page cannot be closed.",
    "usage": "close-page --page-id <page-id:number> [--raw <json>]",
    "flags": "--page-id <page-id:number> [--raw <json>]"
  },
  {
    "name": "drag",
    "description": "Drag an element onto another element",
    "usage": "drag --from-uid <from-uid> --to-uid <to-uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--from-uid <from-uid> --to-uid <to-uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "emulate",
    "description": "Emulates various features on the selected page.",
    "usage": "emulate [--network-conditions <network-conditions:No emulation|Offline|Slow 3G|Fast 3G|Slow 4G|Fast 4G>] [--cpu-throttling-rate <cpu-throttling-rate:number>] [--geolocation <geolocation>] [--user-agent <user-agent>] [--color-scheme <color-scheme:dark|light|auto>] [--raw <json>]",
    "flags": "[--network-conditions <network-conditions:No emulation|Offline|Slow 3G|Fast 3G|Slow 4G|Fast 4G>] [--cpu-throttling-rate <cpu-throttling-rate:number>] [--geolocation <geolocation>] [--user-agent <user-agent>] [--color-scheme <color-scheme:dark|light|auto>] [--raw <json>]"
  },
  {
    "name": "evaluate-script",
    "description": "Evaluate a JavaScript function inside the currently selected page. Returns the response as JSON\nso returned values have to JSON-serializable.",
    "usage": "evaluate-script --function <function> [--args <args:value1,value2>] [--raw <json>]",
    "flags": "--function <function> [--args <args:value1,value2>] [--raw <json>]"
  },
  {
    "name": "fill",
    "description": "Type text into a input, text area or select an option from a <select> element.",
    "usage": "fill --uid <uid> --value <value> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--uid <uid> --value <value> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "fill-form",
    "description": "Fill out multiple form elements at once",
    "usage": "fill-form --elements <elements:value1,value2> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--elements <elements:value1,value2> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "get-console-message",
    "description": "Gets a console message by its ID. You can get all messages by calling list_console_messages.",
    "usage": "get-console-message --msgid <msgid:number> [--raw <json>]",
    "flags": "--msgid <msgid:number> [--raw <json>]"
  },
  {
    "name": "get-network-request",
    "description": "Gets a network request by an optional reqid, if omitted returns the currently selected request in the DevTools Network panel.",
    "usage": "get-network-request [--reqid <reqid:number>] [--request-file-path <request-file-path>] [--response-file-path <response-file-path>] [--raw <json>]",
    "flags": "[--reqid <reqid:number>] [--request-file-path <request-file-path>] [--response-file-path <response-file-path>] [--raw <json>]"
  },
  {
    "name": "handle-dialog",
    "description": "If a browser dialog was opened, use this command to handle it",
    "usage": "handle-dialog --action <action:accept|dismiss> [--prompt-text <prompt-text>] [--raw <json>]",
    "flags": "--action <action:accept|dismiss> [--prompt-text <prompt-text>] [--raw <json>]"
  },
  {
    "name": "hover",
    "description": "Hover over the provided element",
    "usage": "hover --uid <uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--uid <uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "list-console-messages",
    "description": "List all console messages for the currently selected page since the last navigation.",
    "usage": "list-console-messages [--page-size <page-size:number>] [--page-idx <page-idx:number>] [--types <types:log|debug|info|error|warn|dir|dirxml|table|trace|clear|startGroup|startGroupCollapsed|endGroup|assert|profile|profileEnd|count|timeEnd|verbose|issue>] [--include-preserved-messages <include-preserved-messages:true|false>] [--raw <json>]",
    "flags": "[--page-size <page-size:number>] [--page-idx <page-idx:number>] [--types <types:log|debug|info|error|warn|dir|dirxml|table|trace|clear|startGroup|startGroupCollapsed|endGroup|assert|profile|profileEnd|count|timeEnd|verbose|issue>] [--include-preserved-messages <include-preserved-messages:true|false>] [--raw <json>]"
  },
  {
    "name": "list-network-requests",
    "description": "List all requests for the currently selected page since the last navigation.",
    "usage": "list-network-requests [--page-size <page-size:number>] [--page-idx <page-idx:number>] [--resource-types <resource-types:document|stylesheet|image|media|font|script|texttrack|xhr|fetch|prefetch|eventsource|websocket|manifest|signedexchange|ping|cspviolationreport|preflight|fedcm|other>] [--include-preserved-requests <include-preserved-requests:true|false>] [--raw <json>]",
    "flags": "[--page-size <page-size:number>] [--page-idx <page-idx:number>] [--resource-types <resource-types:document|stylesheet|image|media|font|script|texttrack|xhr|fetch|prefetch|eventsource|websocket|manifest|signedexchange|ping|cspviolationreport|preflight|fedcm|other>] [--include-preserved-requests <include-preserved-requests:true|false>] [--raw <json>]"
  },
  {
    "name": "list-pages",
    "description": "Get a list of pages open in the browser.",
    "usage": "list-pages [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "navigate-page",
    "description": "Navigates the currently selected page to a URL.",
    "usage": "navigate-page [--type <type:url|back|forward|reload>] [--url <url>] [--ignore-cache <ignore-cache:true|false>] [--handle-before-unload <handle-before-unload:accept|decline>] [--init-script <init-script>] [--raw <json>]",
    "flags": "[--type <type:url|back|forward|reload>] [--url <url>] [--ignore-cache <ignore-cache:true|false>] [--handle-before-unload <handle-before-unload:accept|decline>] [--init-script <init-script>] [--raw <json>]"
  },
  {
    "name": "new-page",
    "description": "Creates a new page",
    "usage": "new-page --url <url> [--background <background:true|false>] [--timeout <timeout:number>] [--raw <json>]",
    "flags": "--url <url> [--background <background:true|false>] [--timeout <timeout:number>] [--raw <json>]"
  },
  {
    "name": "performance-analyze-insight",
    "description": "Provides more detailed information on a specific Performance Insight of an insight set that was highlighted in the results of a trace recording.",
    "usage": "performance-analyze-insight --insight-set-id <insight-set-id> --insight-name <insight-name> [--raw <json>]",
    "flags": "--insight-set-id <insight-set-id> --insight-name <insight-name> [--raw <json>]"
  },
  {
    "name": "performance-start-trace",
    "description": "Starts a performance trace recording on the selected page. This can be used to look for performance problems and insights to improve the performance of the page. It will also report Core Web Vital (CWV) scores for the page.",
    "usage": "performance-start-trace --reload <reload:true|false> --auto-stop <auto-stop:true|false> [--file-path <file-path>] [--raw <json>]",
    "flags": "--reload <reload:true|false> --auto-stop <auto-stop:true|false> [--file-path <file-path>] [--raw <json>]"
  },
  {
    "name": "performance-stop-trace",
    "description": "Stops the active performance trace recording on the selected page.",
    "usage": "performance-stop-trace [--file-path <file-path>] [--raw <json>]",
    "flags": "[--file-path <file-path>] [--raw <json>]"
  },
  {
    "name": "press-key",
    "description": "Press a key or key combination. Use this when other input methods like fill() cannot be used (e.g., keyboard shortcuts, navigation keys, or special key combinations).",
    "usage": "press-key --key <key> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--key <key> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "resize-page",
    "description": "Resizes the selected page's window so that the page has specified dimension",
    "usage": "resize-page --width <width:number> --height <height:number> [--raw <json>]",
    "flags": "--width <width:number> --height <height:number> [--raw <json>]"
  },
  {
    "name": "select-page",
    "description": "Select a page as a context for future tool calls.",
    "usage": "select-page --page-id <page-id:number> [--bring-to-front <bring-to-front:true|false>] [--raw <json>]",
    "flags": "--page-id <page-id:number> [--bring-to-front <bring-to-front:true|false>] [--raw <json>]"
  },
  {
    "name": "take-screenshot",
    "description": "Take a screenshot of the page or element.",
    "usage": "take-screenshot [--format <format:png|jpeg|webp>] [--quality <quality:number>] [--uid <uid>] [--full-page <full-page:true|false>] [--file-path <file-path>] [--raw <json>]",
    "flags": "[--format <format:png|jpeg|webp>] [--quality <quality:number>] [--uid <uid>] [--full-page <full-page:true|false>] [--file-path <file-path>] [--raw <json>]"
  },
  {
    "name": "take-snapshot",
    "description": "Take a text snapshot of the currently selected page based on the a11y tree. The snapshot lists page elements along with a unique\nidentifier (uid). Always use the latest snapshot. Prefer taking a snapshot over taking a screenshot. The snapshot indicates the element selected\nin the DevTools Elements panel (if any).",
    "usage": "take-snapshot [--verbose <verbose:true|false>] [--file-path <file-path>] [--raw <json>]",
    "flags": "[--verbose <verbose:true|false>] [--file-path <file-path>] [--raw <json>]"
  },
  {
    "name": "upload-file",
    "description": "Upload a file through a provided element.",
    "usage": "upload-file --uid <uid> --file-path <file-path> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]",
    "flags": "--uid <uid> --file-path <file-path> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]"
  },
  {
    "name": "wait-for",
    "description": "Wait for the specified text to appear on the selected page.",
    "usage": "wait-for --text <text> [--timeout <timeout:number>] [--raw <json>]",
    "flags": "--text <text> [--timeout <timeout:number>] [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-01-30T21:37:37.831Z",
  "generator": {
    "name": "mcporter",
    "version": "0.7.3"
  },
  "server": {
    "name": "chrome-devtools",
    "source": {
      "kind": "local",
      "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
    },
    "definition": {
      "name": "chrome-devtools",
      "description": "Chrome DevTools MCP server",
      "command": {
        "kind": "stdio",
        "command": "npx",
        "args": [
          "-y",
          "chrome-devtools-mcp@latest"
        ],
        "cwd": "/Users/tim/.openclaw/workspace/config"
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "chrome-devtools",
    "configPath": "/Users/tim/.openclaw/workspace/config/mcporter.json",
    "runtime": "bun",
    "bundler": "bun",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "click": "function click(uid: string, dblClick?: boolean, includeSnapshot?: boolean);",
  "close-page": "function close_page(pageId: number);",
  "drag": "function drag(from_uid: string, to_uid: string, includeSnapshot?: boolean);",
  "emulate": "function emulate(networkConditions?: \"No emulation\" | \"Offline\" | \"Slow 3G\" | \"Fast 3G\" | \"Slow 4G\" | \"Fast 4G\", cpuThrottlingRate?: number, geolocation?: unknown, userAgent?: string, colorScheme?: \"dark\" | \"light\" | \"auto\");",
  "evaluate-script": "function evaluate_script(function: string, args?: string[]);",
  "fill": "function fill(uid: string, value: string, includeSnapshot?: boolean);",
  "fill-form": "function fill_form(elements: string[], includeSnapshot?: boolean);",
  "get-console-message": "function get_console_message(msgid: number);",
  "get-network-request": "function get_network_request(reqid?: number, requestFilePath?: string, responseFilePath?: string);",
  "handle-dialog": "function handle_dialog(action: \"accept\" | \"dismiss\", promptText?: string);",
  "hover": "function hover(uid: string, includeSnapshot?: boolean);",
  "list-console-messages": "function list_console_messages(pageSize?: number, pageIdx?: number, types?: \"log\" | \"debug\" | \"info\" | \"error\" | \"warn\" | \"dir\" | \"dirxml\" | \"table\" | \"trace\" | \"clear\" | \"startGroup\" | \"startGroupCollapsed\" | \"endGroup\" | \"assert\" | \"profile\" | \"profileEnd\" | \"count\" | \"timeEnd\" | \"verbose\" | \"issue\", includePreservedMessages?: boolean);",
  "list-network-requests": "function list_network_requests(pageSize?: number, pageIdx?: number, resourceTypes?: \"document\" | \"stylesheet\" | \"image\" | \"media\" | \"font\" | \"script\" | \"texttrack\" | \"xhr\" | \"fetch\" | \"prefetch\" | \"eventsource\" | \"websocket\" | \"manifest\" | \"signedexchange\" | \"ping\" | \"cspviolationreport\" | \"preflight\" | \"fedcm\" | \"other\", includePreservedRequests?: boolean);",
  "list-pages": "function list_pages();",
  "navigate-page": "function navigate_page(type?: \"url\" | \"back\" | \"forward\" | \"reload\", url?: string, ignoreCache?: boolean, handleBeforeUnload?: \"accept\" | \"decline\", initScript?: string);",
  "new-page": "function new_page(url: string, background?: boolean, timeout?: number);",
  "performance-analyze-insight": "function performance_analyze_insight(insightSetId: string, insightName: string);",
  "performance-start-trace": "function performance_start_trace(reload: boolean, autoStop: boolean, filePath?: string);",
  "performance-stop-trace": "function performance_stop_trace(filePath?: string);",
  "press-key": "function press_key(key: string, includeSnapshot?: boolean);",
  "resize-page": "function resize_page(width: number, height: number);",
  "select-page": "function select_page(pageId: number, bringToFront?: boolean);",
  "take-screenshot": "function take_screenshot(format?: \"png\" | \"jpeg\" | \"webp\", quality?: number, uid?: string, fullPage?: boolean, filePath?: string);",
  "take-snapshot": "function take_snapshot(verbose?: boolean, filePath?: string);",
  "upload-file": "function upload_file(uid: string, filePath: string, includeSnapshot?: boolean);",
  "wait-for": "function wait_for(text: string, timeout?: number);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("click")
	.summary("click --uid <uid> [--dbl-click <dbl-click:true|false>] [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Clicks on the provided element")
	.usage("--uid <uid> [--dbl-click <dbl-click:true|false>] [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--uid <uid>", "The uid of an element on the page from the page content snapshot (example: example-id)")
	.option("--dbl-click <dbl-click:true|false>", "Set to true for double clicks. Default is false. (example: true)", (value) => value !== 'false')
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.uid !== undefined) args.uid = cmdOpts.uid;
		if (cmdOpts.dblClick !== undefined) args.dblClick = cmdOpts.dblClick;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.click as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.click(uid: \"example-id\", dblClick: true, inc, ...)");

program
	.command("close-page")
	.summary("close-page --page-id <page-id:number> [--raw <json>]")
	.description("Closes the page by its index. The last open page cannot be closed.")
	.usage("--page-id <page-id:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--page-id <page-id:number>", "The ID of the page to close. Call list_pages to list pages. (example: 1)", (value) => parseFloat(value))
	
	.alias("close_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.pageId !== undefined) args.pageId = cmdOpts.pageId;
			const call = (proxy.closePage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.close_page(pageId: 1)");

program
	.command("drag")
	.summary("drag --from-uid <from-uid> --to-uid <to-uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Drag an element onto another element")
	.usage("--from-uid <from-uid> --to-uid <to-uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--from-uid <from-uid>", "The uid of the element to drag (example: example-id)")
	.requiredOption("--to-uid <to-uid>", "The uid of the element to drop into (example: example-id)")
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.fromUid !== undefined) args.from_uid = cmdOpts.fromUid;
		if (cmdOpts.toUid !== undefined) args.to_uid = cmdOpts.toUid;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.drag as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.drag(from_uid: \"example-id\", to_uid: \"exampl, ...)");

program
	.command("emulate")
	.summary("emulate [--network-conditions <network-conditions:No emulation|Offline|Slow 3G|Fast 3G|Slow 4G|Fast 4G>] [--cpu-throttling-rate <cpu-throttling-rate:number>] [--geolocation <geolocation>] [--user-agent <user-agent>] [--color-scheme <color-scheme:dark|light|auto>] [--raw <json>]")
	.description("Emulates various features on the selected page.")
	.usage("[--network-conditions <network-conditions:No emulation|Offline|Slow 3G|Fast 3G|Slow 4G|Fast 4G>] [--cpu-throttling-rate <cpu-throttling-rate:number>] [--geolocation <geolocation>] [--user-agent <user-agent>] [--color-scheme <color-scheme:dark|light|auto>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--network-conditions <network-conditions:No emulation|Offline|Slow 3G|Fast 3G|Slow 4G|Fast 4G>", "Throttle network. Set to \"No emulation\" to disable. If omitted, conditions remain unchanged. (choices: No emulation, Offline, Slow 3G, Fast 3G, Slow 4G, Fast 4G; example: No emulation)")
	.option("--cpu-throttling-rate <cpu-throttling-rate:number>", "Represents the CPU slowdown factor. Set the rate to 1 to disable throttling. If omitted, throttling remains unchanged. (example: 1)", (value) => parseFloat(value))
	.option("--geolocation <geolocation>", "Geolocation to emulate. Set to null to clear the geolocation override.")
	.option("--user-agent <user-agent>", "User agent to emulate. Set to null to clear the user agent override.")
	.option("--color-scheme <color-scheme:dark|light|auto>", "Emulate the dark or the light mode. Set to \"auto\" to reset to the default. (choices: dark, light, auto; example: dark)")
	.option("--viewport <viewport>", "Viewport to emulate. Set to null to reset to the default viewport.")
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.networkConditions !== undefined) args.networkConditions = cmdOpts.networkConditions;
		if (cmdOpts.cpuThrottlingRate !== undefined) args.cpuThrottlingRate = cmdOpts.cpuThrottlingRate;
		if (cmdOpts.geolocation !== undefined) args.geolocation = cmdOpts.geolocation;
		if (cmdOpts.userAgent !== undefined) args.userAgent = cmdOpts.userAgent;
		if (cmdOpts.colorScheme !== undefined) args.colorScheme = cmdOpts.colorScheme;
		if (cmdOpts.viewport !== undefined) args.viewport = cmdOpts.viewport;
			const call = (proxy.emulate as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.emulate(networkConditions: \"No emulation\", c, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (1): viewport" + '\n');

program
	.command("evaluate-script")
	.summary("evaluate-script --function <function> [--args <args:value1,value2>] [--raw <json>]")
	.description("Evaluate a JavaScript function inside the currently selected page. Returns the response as JSON\nso returned values have to JSON-serializable.")
	.usage("--function <function> [--args <args:value1,value2>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--function <function>", "A JavaScript function declaration to be executed by the tool in the currently selected page.\nExample without arguments: `() => {\n  return document.title\n}` or `async () => {\n  return await fetch(\"example.com\")\n}`.\nExample with arguments: `(el) => {\n  return el.innerText;\n}`\n")
	.option("--args <args:value1,value2>", "An optional list of arguments to pass to the function. (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	
	.alias("evaluate_script")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.function !== undefined) args.function = cmdOpts.function;
		if (cmdOpts.args !== undefined) args.args = cmdOpts.args;
			const call = (proxy.evaluateScript as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.evaluate_script(function: \"value\", args: [\"v, ...)");

program
	.command("fill")
	.summary("fill --uid <uid> --value <value> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Type text into a input, text area or select an option from a <select> element.")
	.usage("--uid <uid> --value <value> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--uid <uid>", "The uid of an element on the page from the page content snapshot (example: example-id)")
	.requiredOption("--value <value>", "The value to fill in")
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.uid !== undefined) args.uid = cmdOpts.uid;
		if (cmdOpts.value !== undefined) args.value = cmdOpts.value;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.fill as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.fill(uid: \"example-id\", value: \"value\", incl, ...)");

program
	.command("fill-form")
	.summary("fill-form --elements <elements:value1,value2> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Fill out multiple form elements at once")
	.usage("--elements <elements:value1,value2> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--elements <elements:value1,value2>", "Elements from snapshot to fill out. (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	
	.alias("fill_form")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.elements !== undefined) args.elements = cmdOpts.elements;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.fillForm as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.fill_form(elements: [\"value1\", \"value2\"], in, ...)");

program
	.command("get-console-message")
	.summary("get-console-message --msgid <msgid:number> [--raw <json>]")
	.description("Gets a console message by its ID. You can get all messages by calling list_console_messages.")
	.usage("--msgid <msgid:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--msgid <msgid:number>", "The msgid of a console message on the page from the listed console messages (example: 1)", (value) => parseFloat(value))
	
	.alias("get_console_message")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.msgid !== undefined) args.msgid = cmdOpts.msgid;
			const call = (proxy.getConsoleMessage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.get_console_message(msgid: 1)");

program
	.command("get-network-request")
	.summary("get-network-request [--reqid <reqid:number>] [--request-file-path <request-file-path>] [--response-file-path <response-file-path>] [--raw <json>]")
	.description("Gets a network request by an optional reqid, if omitted returns the currently selected request in the DevTools Network panel.")
	.usage("[--reqid <reqid:number>] [--request-file-path <request-file-path>] [--response-file-path <response-file-path>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--reqid <reqid:number>", "The reqid of the network request. If omitted returns the currently selected request in the DevTools Network panel. (example: 1)", (value) => parseFloat(value))
	.option("--request-file-path <request-file-path>", "The absolute or relative path to save the request body to. If omitted, the body is returned inline. (example: /path/to/file.md)")
	.option("--response-file-path <response-file-path>", "The absolute or relative path to save the response body to. If omitted, the body is returned inline. (example: /path/to/file.md)")
	
	.alias("get_network_request")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.reqid !== undefined) args.reqid = cmdOpts.reqid;
		if (cmdOpts.requestFilePath !== undefined) args.requestFilePath = cmdOpts.requestFilePath;
		if (cmdOpts.responseFilePath !== undefined) args.responseFilePath = cmdOpts.responseFilePath;
			const call = (proxy.getNetworkRequest as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.get_network_request(reqid: 1, requestFilePat, ...)");

program
	.command("handle-dialog")
	.summary("handle-dialog --action <action:accept|dismiss> [--prompt-text <prompt-text>] [--raw <json>]")
	.description("If a browser dialog was opened, use this command to handle it")
	.usage("--action <action:accept|dismiss> [--prompt-text <prompt-text>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--action <action:accept|dismiss>", "Whether to dismiss or accept the dialog (choices: accept, dismiss; example: accept)")
	.option("--prompt-text <prompt-text>", "Optional prompt text to enter into the dialog.")
	
	.alias("handle_dialog")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.action !== undefined) args.action = cmdOpts.action;
		if (cmdOpts.promptText !== undefined) args.promptText = cmdOpts.promptText;
			const call = (proxy.handleDialog as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.handle_dialog(action: \"accept\")");

program
	.command("hover")
	.summary("hover --uid <uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Hover over the provided element")
	.usage("--uid <uid> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--uid <uid>", "The uid of an element on the page from the page content snapshot (example: example-id)")
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.uid !== undefined) args.uid = cmdOpts.uid;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.hover as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.hover(uid: \"example-id\", includeSnapshot: true)");

program
	.command("list-console-messages")
	.summary("list-console-messages [--page-size <page-size:number>] [--page-idx <page-idx:number>] [--types <types:log|debug|info|error|warn|dir|dirxml|table|trace|clear|startGroup|startGroupCollapsed|endGroup|assert|profile|profileEnd|count|timeEnd|verbose|issue>] [--include-preserved-messages <include-preserved-messages:true|false>] [--raw <json>]")
	.description("List all console messages for the currently selected page since the last navigation.")
	.usage("[--page-size <page-size:number>] [--page-idx <page-idx:number>] [--types <types:log|debug|info|error|warn|dir|dirxml|table|trace|clear|startGroup|startGroupCollapsed|endGroup|assert|profile|profileEnd|count|timeEnd|verbose|issue>] [--include-preserved-messages <include-preserved-messages:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--page-size <page-size:number>", "Maximum number of messages to return. When omitted, returns all requests. (example: 1)", (value) => parseFloat(value))
	.option("--page-idx <page-idx:number>", "Page number to return (0-based). When omitted, returns the first page. (example: 1)", (value) => parseFloat(value))
	.option("--types <types:log|debug|info|error|warn|dir|dirxml|table|trace|clear|startGroup|startGroupCollapsed|endGroup|assert|profile|profileEnd|count|timeEnd|verbose|issue>", "Filter messages to only return messages of the specified resource types. When omitted or empty, returns all messages. (choices: log, debug, info, error, warn, dir, dirxml, table, trace, clear, startGroup, startGroupCollapsed, endGroup, assert, profile, profileEnd, count, timeEnd, verbose, issue; example: log)", (value) => value.split(',').map((v) => v.trim()))
	.option("--include-preserved-messages <include-preserved-messages:true|false>", "Set to true to return the preserved messages over the last 3 navigations. (default: false; example: false)", (value) => value !== 'false')
	
	.alias("list_console_messages")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.pageSize !== undefined) args.pageSize = cmdOpts.pageSize;
		if (cmdOpts.pageIdx !== undefined) args.pageIdx = cmdOpts.pageIdx;
		if (cmdOpts.types !== undefined) args.types = cmdOpts.types;
		if (cmdOpts.includePreservedMessages !== undefined) args.includePreservedMessages = cmdOpts.includePreservedMessages;
			const call = (proxy.listConsoleMessages as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.list_console_messages(pageSize: 1, pageIdx:, ...)");

program
	.command("list-network-requests")
	.summary("list-network-requests [--page-size <page-size:number>] [--page-idx <page-idx:number>] [--resource-types <resource-types:document|stylesheet|image|media|font|script|texttrack|xhr|fetch|prefetch|eventsource|websocket|manifest|signedexchange|ping|cspviolationreport|preflight|fedcm|other>] [--include-preserved-requests <include-preserved-requests:true|false>] [--raw <json>]")
	.description("List all requests for the currently selected page since the last navigation.")
	.usage("[--page-size <page-size:number>] [--page-idx <page-idx:number>] [--resource-types <resource-types:document|stylesheet|image|media|font|script|texttrack|xhr|fetch|prefetch|eventsource|websocket|manifest|signedexchange|ping|cspviolationreport|preflight|fedcm|other>] [--include-preserved-requests <include-preserved-requests:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--page-size <page-size:number>", "Maximum number of requests to return. When omitted, returns all requests. (example: 1)", (value) => parseFloat(value))
	.option("--page-idx <page-idx:number>", "Page number to return (0-based). When omitted, returns the first page. (example: 1)", (value) => parseFloat(value))
	.option("--resource-types <resource-types:document|stylesheet|image|media|font|script|texttrack|xhr|fetch|prefetch|eventsource|websocket|manifest|signedexchange|ping|cspviolationreport|preflight|fedcm|other>", "Filter requests to only return requests of the specified resource types. When omitted or empty, returns all requests. (choices: document, stylesheet, image, media, font, script, texttrack, xhr, fetch, prefetch, eventsource, websocket, manifest, signedexchange, ping, cspviolationreport, preflight, fedcm, other; example: document)", (value) => value.split(',').map((v) => v.trim()))
	.option("--include-preserved-requests <include-preserved-requests:true|false>", "Set to true to return the preserved requests over the last 3 navigations. (default: false; example: false)", (value) => value !== 'false')
	
	.alias("list_network_requests")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.pageSize !== undefined) args.pageSize = cmdOpts.pageSize;
		if (cmdOpts.pageIdx !== undefined) args.pageIdx = cmdOpts.pageIdx;
		if (cmdOpts.resourceTypes !== undefined) args.resourceTypes = cmdOpts.resourceTypes;
		if (cmdOpts.includePreservedRequests !== undefined) args.includePreservedRequests = cmdOpts.includePreservedRequests;
			const call = (proxy.listNetworkRequests as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.list_network_requests(pageSize: 1, pageIdx:, ...)");

program
	.command("list-pages")
	.summary("list-pages [--raw <json>]")
	.description("Get a list of pages open in the browser.")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("list_pages")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.listPages as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.list_pages()");

program
	.command("navigate-page")
	.summary("navigate-page [--type <type:url|back|forward|reload>] [--url <url>] [--ignore-cache <ignore-cache:true|false>] [--handle-before-unload <handle-before-unload:accept|decline>] [--init-script <init-script>] [--raw <json>]")
	.description("Navigates the currently selected page to a URL.")
	.usage("[--type <type:url|back|forward|reload>] [--url <url>] [--ignore-cache <ignore-cache:true|false>] [--handle-before-unload <handle-before-unload:accept|decline>] [--init-script <init-script>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--type <type:url|back|forward|reload>", "Navigate the page by URL, back or forward in history, or reload. (choices: url, back, forward, reload; example: url)")
	.option("--url <url>", "Target URL (only type=url)")
	.option("--ignore-cache <ignore-cache:true|false>", "Whether to ignore cache on reload. (example: true)", (value) => value !== 'false')
	.option("--handle-before-unload <handle-before-unload:accept|decline>", "Whether to auto accept or beforeunload dialogs triggered by this navigation. Default is accept. (choices: accept, decline; example: accept)")
	.option("--init-script <init-script>", "A JavaScript script to be executed on each new document before any other scripts for the next navigation.")
	.option("--timeout <timeout:number>", "Maximum wait time in milliseconds. If set to 0, the default timeout will be used. (example: 1)", (value) => parseFloat(value))
	
	.alias("navigate_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.type !== undefined) args.type = cmdOpts.type;
		if (cmdOpts.url !== undefined) args.url = cmdOpts.url;
		if (cmdOpts.ignoreCache !== undefined) args.ignoreCache = cmdOpts.ignoreCache;
		if (cmdOpts.handleBeforeUnload !== undefined) args.handleBeforeUnload = cmdOpts.handleBeforeUnload;
		if (cmdOpts.initScript !== undefined) args.initScript = cmdOpts.initScript;
		if (cmdOpts.timeout !== undefined) args.timeout = cmdOpts.timeout;
			const call = (proxy.navigatePage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.navigate_page(type: \"url\", ignoreCache: true, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (1): timeout" + '\n');

program
	.command("new-page")
	.summary("new-page --url <url> [--background <background:true|false>] [--timeout <timeout:number>] [--raw <json>]")
	.description("Creates a new page")
	.usage("--url <url> [--background <background:true|false>] [--timeout <timeout:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--url <url>", "URL to load in a new page.")
	.option("--background <background:true|false>", "Whether to open the page in the background without bringing it to the front. Default is false (foreground). (example: true)", (value) => value !== 'false')
	.option("--timeout <timeout:number>", "Maximum wait time in milliseconds. If set to 0, the default timeout will be used. (example: 1)", (value) => parseFloat(value))
	
	.alias("new_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.url !== undefined) args.url = cmdOpts.url;
		if (cmdOpts.background !== undefined) args.background = cmdOpts.background;
		if (cmdOpts.timeout !== undefined) args.timeout = cmdOpts.timeout;
			const call = (proxy.newPage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.new_page(url: \"https://example.com\", backgro, ...)");

program
	.command("performance-analyze-insight")
	.summary("performance-analyze-insight --insight-set-id <insight-set-id> --insight-name <insight-name> [--raw <json>]")
	.description("Provides more detailed information on a specific Performance Insight of an insight set that was highlighted in the results of a trace recording.")
	.usage("--insight-set-id <insight-set-id> --insight-name <insight-name> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--insight-set-id <insight-set-id>", "The id for the specific insight set. Only use the ids given in the \"Available insight sets\" list. (example: example-id)")
	.requiredOption("--insight-name <insight-name>", "The name of the Insight you want more information on. For example: \"DocumentLatency\" or \"LCPBreakdown\"")
	
	.alias("performance_analyze_insight")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.insightSetId !== undefined) args.insightSetId = cmdOpts.insightSetId;
		if (cmdOpts.insightName !== undefined) args.insightName = cmdOpts.insightName;
			const call = (proxy.performanceAnalyzeInsight as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.performance_analyze_insight(insightSetId: \"e, ...)");

program
	.command("performance-start-trace")
	.summary("performance-start-trace --reload <reload:true|false> --auto-stop <auto-stop:true|false> [--file-path <file-path>] [--raw <json>]")
	.description("Starts a performance trace recording on the selected page. This can be used to look for performance problems and insights to improve the performance of the page. It will also report Core Web Vital (CWV) scores for the page.")
	.usage("--reload <reload:true|false> --auto-stop <auto-stop:true|false> [--file-path <file-path>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--reload <reload:true|false>", "Determines if, once tracing has started, the current selected page should be automatically reloaded. Navigate the page to the right URL using the navigate_page tool BEFORE starting the trace if reload or autoStop is set to true. (example: true)", (value) => value !== 'false')
	.requiredOption("--auto-stop <auto-stop:true|false>", "Determines if the trace recording should be automatically stopped. (example: true)", (value) => value !== 'false')
	.option("--file-path <file-path>", "The absolute file path, or a file path relative to the current working directory, to save the raw trace data. For example, trace.json.gz (compressed) or trace.json (uncompressed). (example: /path/to/file.md)")
	
	.alias("performance_start_trace")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.reload !== undefined) args.reload = cmdOpts.reload;
		if (cmdOpts.autoStop !== undefined) args.autoStop = cmdOpts.autoStop;
		if (cmdOpts.filePath !== undefined) args.filePath = cmdOpts.filePath;
			const call = (proxy.performanceStartTrace as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.performance_start_trace(reload: true, autoSt, ...)");

program
	.command("performance-stop-trace")
	.summary("performance-stop-trace [--file-path <file-path>] [--raw <json>]")
	.description("Stops the active performance trace recording on the selected page.")
	.usage("[--file-path <file-path>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--file-path <file-path>", "The absolute file path, or a file path relative to the current working directory, to save the raw trace data. For example, trace.json.gz (compressed) or trace.json (uncompressed). (example: /path/to/file.md)")
	
	.alias("performance_stop_trace")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.filePath !== undefined) args.filePath = cmdOpts.filePath;
			const call = (proxy.performanceStopTrace as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.performance_stop_trace(filePath: \"/path/to/f, ...)");

program
	.command("press-key")
	.summary("press-key --key <key> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Press a key or key combination. Use this when other input methods like fill() cannot be used (e.g., keyboard shortcuts, navigation keys, or special key combinations).")
	.usage("--key <key> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--key <key>", "A key or a combination (e.g., \"Enter\", \"Control+A\", \"Control++\", \"Control+Shift+R\"). Modifiers: Control, Shift, Alt, Meta")
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	
	.alias("press_key")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.key !== undefined) args.key = cmdOpts.key;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.pressKey as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.press_key(key: \"value\", includeSnapshot: true)");

program
	.command("resize-page")
	.summary("resize-page --width <width:number> --height <height:number> [--raw <json>]")
	.description("Resizes the selected page's window so that the page has specified dimension")
	.usage("--width <width:number> --height <height:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--width <width:number>", "Page width (example: 1)", (value) => parseFloat(value))
	.requiredOption("--height <height:number>", "Page height (example: 1)", (value) => parseFloat(value))
	
	.alias("resize_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.width !== undefined) args.width = cmdOpts.width;
		if (cmdOpts.height !== undefined) args.height = cmdOpts.height;
			const call = (proxy.resizePage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.resize_page(width: 1, height: 1)");

program
	.command("select-page")
	.summary("select-page --page-id <page-id:number> [--bring-to-front <bring-to-front:true|false>] [--raw <json>]")
	.description("Select a page as a context for future tool calls.")
	.usage("--page-id <page-id:number> [--bring-to-front <bring-to-front:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--page-id <page-id:number>", "The ID of the page to select. Call list_pages to get available pages. (example: 1)", (value) => parseFloat(value))
	.option("--bring-to-front <bring-to-front:true|false>", "Whether to focus the page and bring it to the top. (example: true)", (value) => value !== 'false')
	
	.alias("select_page")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.pageId !== undefined) args.pageId = cmdOpts.pageId;
		if (cmdOpts.bringToFront !== undefined) args.bringToFront = cmdOpts.bringToFront;
			const call = (proxy.selectPage as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.select_page(pageId: 1, bringToFront: true)");

program
	.command("take-screenshot")
	.summary("take-screenshot [--format <format:png|jpeg|webp>] [--quality <quality:number>] [--uid <uid>] [--full-page <full-page:true|false>] [--file-path <file-path>] [--raw <json>]")
	.description("Take a screenshot of the page or element.")
	.usage("[--format <format:png|jpeg|webp>] [--quality <quality:number>] [--uid <uid>] [--full-page <full-page:true|false>] [--file-path <file-path>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--format <format:png|jpeg|webp>", "Type of format to save the screenshot as. Default is \"png\" (choices: png, jpeg, webp; default: png; example: png)")
	.option("--quality <quality:number>", "Compression quality for JPEG and WebP formats (0-100). Higher values mean better quality but larger file sizes. Ignored for PNG format. (example: 1)", (value) => parseFloat(value))
	.option("--uid <uid>", "The uid of an element on the page from the page content snapshot. If omitted takes a pages screenshot. (example: example-id)")
	.option("--full-page <full-page:true|false>", "If set to true takes a screenshot of the full page instead of the currently visible viewport. Incompatible with uid. (example: true)", (value) => value !== 'false')
	.option("--file-path <file-path>", "The absolute path, or a path relative to the current working directory, to save the screenshot to instead of attaching it to the response. (example: /path/to/file.md)")
	
	.alias("take_screenshot")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.format !== undefined) args.format = cmdOpts.format;
		if (cmdOpts.quality !== undefined) args.quality = cmdOpts.quality;
		if (cmdOpts.uid !== undefined) args.uid = cmdOpts.uid;
		if (cmdOpts.fullPage !== undefined) args.fullPage = cmdOpts.fullPage;
		if (cmdOpts.filePath !== undefined) args.filePath = cmdOpts.filePath;
			const call = (proxy.takeScreenshot as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.take_screenshot(format: \"png\", quality: 1, u, ...)");

program
	.command("take-snapshot")
	.summary("take-snapshot [--verbose <verbose:true|false>] [--file-path <file-path>] [--raw <json>]")
	.description("Take a text snapshot of the currently selected page based on the a11y tree. The snapshot lists page elements along with a unique\nidentifier (uid). Always use the latest snapshot. Prefer taking a snapshot over taking a screenshot. The snapshot indicates the element selected\nin the DevTools Elements panel (if any).")
	.usage("[--verbose <verbose:true|false>] [--file-path <file-path>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--verbose <verbose:true|false>", "Whether to include all possible information available in the full a11y tree. Default is false. (example: true)", (value) => value !== 'false')
	.option("--file-path <file-path>", "The absolute path, or a path relative to the current working directory, to save the snapshot to instead of attaching it to the response. (example: /path/to/file.md)")
	
	.alias("take_snapshot")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.verbose !== undefined) args.verbose = cmdOpts.verbose;
		if (cmdOpts.filePath !== undefined) args.filePath = cmdOpts.filePath;
			const call = (proxy.takeSnapshot as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.take_snapshot(verbose: true, filePath: \"/pat, ...)");

program
	.command("upload-file")
	.summary("upload-file --uid <uid> --file-path <file-path> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.description("Upload a file through a provided element.")
	.usage("--uid <uid> --file-path <file-path> [--include-snapshot <include-snapshot:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--uid <uid>", "The uid of the file input element or an element that will open file chooser on the page from the page content snapshot (example: example-id)")
	.requiredOption("--file-path <file-path>", "The local path of the file to upload (example: /path/to/file.md)")
	.option("--include-snapshot <include-snapshot:true|false>", "Whether to include a snapshot in the response. Default is false. (example: true)", (value) => value !== 'false')
	
	.alias("upload_file")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.uid !== undefined) args.uid = cmdOpts.uid;
		if (cmdOpts.filePath !== undefined) args.filePath = cmdOpts.filePath;
		if (cmdOpts.includeSnapshot !== undefined) args.includeSnapshot = cmdOpts.includeSnapshot;
			const call = (proxy.uploadFile as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.upload_file(uid: \"example-id\", filePath: \"/p, ...)");

program
	.command("wait-for")
	.summary("wait-for --text <text> [--timeout <timeout:number>] [--raw <json>]")
	.description("Wait for the specified text to appear on the selected page.")
	.usage("--text <text> [--timeout <timeout:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--text <text>", "Text to appear on the page")
	.option("--timeout <timeout:number>", "Maximum wait time in milliseconds. If set to 0, the default timeout will be used. (example: 1)", (value) => parseFloat(value))
	
	.alias("wait_for")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.text !== undefined) args.text = cmdOpts.text;
		if (cmdOpts.timeout !== undefined) args.timeout = cmdOpts.timeout;
			const call = (proxy.waitFor as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call chrome-devtools.wait_for(text: \"value\", timeout: 1)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
