#!/usr/bin/env bun
// @generated by mcporter@0.7.3 on 2026-01-31T03:48:09.875Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "howtocook-mcp",
  "description": "howtocook-mcp",
  "command": {
    "kind": "stdio",
    "command": "npx",
    "args": [
      "-y",
      "howtocook-mcp@latest"
    ],
    "cwd": "/Users/tim/.openclaw/workspace/config"
  },
  "source": {
    "kind": "local",
    "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
    }
  ]
} as const;
const embeddedSchemas = {
  "mcp_howtocook_getAllRecipes": {
    "type": "object",
    "properties": {
      "no_param": {
        "type": "string",
        "description": "无参数"
      }
    },
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "mcp_howtocook_getRecipesByCategory": {
    "type": "object",
    "properties": {
      "category": {
        "type": "string",
        "enum": [
          "水产",
          "早餐",
          "调料",
          "甜品",
          "饮品",
          "荤菜",
          "半成品加工",
          "汤",
          "主食",
          "素菜"
        ],
        "description": "菜谱分类名称，如水产、早餐、荤菜、主食等"
      }
    },
    "required": [
      "category"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "mcp_howtocook_recommendMeals": {
    "type": "object",
    "properties": {
      "allergies": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "过敏原列表，如[\"大蒜\", \"虾\"]"
      },
      "avoidItems": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "忌口食材列表，如[\"葱\", \"姜\"]"
      },
      "peopleCount": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "description": "用餐人数，1-10之间的整数"
      }
    },
    "required": [
      "peopleCount"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "mcp_howtocook_whatToEat": {
    "type": "object",
    "properties": {
      "peopleCount": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "description": "用餐人数，1-10之间的整数，会根据人数推荐合适数量的菜品"
      }
    },
    "required": [
      "peopleCount"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  },
  "mcp_howtocook_getRecipeById": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "菜谱名称或ID，支持模糊匹配菜谱名称"
      }
    },
    "required": [
      "query"
    ],
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
} as const;
const embeddedName = "howtocook-mcp";
const embeddedDescription = "howtocook-mcp";
const generatorInfo = "Generated by mcporter@0.7.3 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "mcp-howtocook-getAllRecipes",
    "description": "获取所有菜谱",
    "usage": "mcp-howtocook-getAllRecipes [--no-param <no-param>] [--raw <json>]",
    "flags": "[--no-param <no-param>] [--raw <json>]"
  },
  {
    "name": "mcp-howtocook-getRecipesByCategory",
    "description": "根据分类查询菜谱，可选分类有: 水产, 早餐, 调料, 甜品, 饮品, 荤菜, 半成品加工, 汤, 主食, 素菜",
    "usage": "mcp-howtocook-getRecipesByCategory --category <category:水产|早餐|调料|甜品|饮品|荤菜|半成品加工|汤|主食|素菜> [--raw <json>]",
    "flags": "--category <category:水产|早餐|调料|甜品|饮品|荤菜|半成品加工|汤|主食|素菜> [--raw <json>]"
  },
  {
    "name": "mcp-howtocook-recommendMeals",
    "description": "根据用户的忌口、过敏原、人数智能推荐菜谱，创建一周的膳食计划以及大致的购物清单",
    "usage": "mcp-howtocook-recommendMeals [--allergies <allergies:value1,value2>] [--avoid-items <avoid-items:value1,value2>] --people-count <people-count:number> [--raw <json>]",
    "flags": "[--allergies <allergies:value1,value2>] [--avoid-items <avoid-items:value1,value2>] --people-count <people-count:number> [--raw <json>]"
  },
  {
    "name": "mcp-howtocook-whatToEat",
    "description": "不知道吃什么？根据人数直接推荐适合的菜品组合",
    "usage": "mcp-howtocook-whatToEat --people-count <people-count:number> [--raw <json>]",
    "flags": "--people-count <people-count:number> [--raw <json>]"
  },
  {
    "name": "mcp-howtocook-getRecipeById",
    "description": "根据菜谱名称或ID查询指定菜谱的完整详情，包括食材、步骤等",
    "usage": "mcp-howtocook-getRecipeById --query <query> [--raw <json>]",
    "flags": "--query <query> [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-01-31T03:48:09.875Z",
  "generator": {
    "name": "mcporter",
    "version": "0.7.3"
  },
  "server": {
    "name": "howtocook-mcp",
    "source": {
      "kind": "local",
      "path": "/Users/tim/.openclaw/workspace/config/mcporter.json"
    },
    "definition": {
      "name": "howtocook-mcp",
      "description": "howtocook-mcp",
      "command": {
        "kind": "stdio",
        "command": "npx",
        "args": [
          "-y",
          "howtocook-mcp@latest"
        ],
        "cwd": "/Users/tim/.openclaw/workspace/config"
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "howtocook-mcp",
    "configPath": "/Users/tim/.openclaw/workspace/config/mcporter.json",
    "runtime": "bun",
    "bundler": "bun",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "mcp-howtocook-getAllRecipes": "function mcp_howtocook_getAllRecipes(no_param?: string);",
  "mcp-howtocook-getRecipesByCategory": "function mcp_howtocook_getRecipesByCategory(category: \"水产\" | \"早餐\" | \"调料\" | \"甜品\" | \"饮品\" | \"荤菜\" | \"半成品加工\" | \"汤\" | \"主食\" | \"素菜\");",
  "mcp-howtocook-recommendMeals": "function mcp_howtocook_recommendMeals(allergies?: string[], avoidItems?: string[], peopleCount: number);",
  "mcp-howtocook-whatToEat": "function mcp_howtocook_whatToEat(peopleCount: number);",
  "mcp-howtocook-getRecipeById": "function mcp_howtocook_getRecipeById(query: string);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("mcp-howtocook-getAllRecipes")
	.summary("mcp-howtocook-getAllRecipes [--no-param <no-param>] [--raw <json>]")
	.description("获取所有菜谱")
	.usage("[--no-param <no-param>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--no-param <no-param>", "无参数")
	
	.alias("mcp_howtocook_getAllRecipes")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.noParam !== undefined) args.no_param = cmdOpts.noParam;
			const call = (proxy.mcpHowtocookGetAllRecipes as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call howtocook-mcp.mcp_howtocook_getAllRecipes()");

program
	.command("mcp-howtocook-getRecipesByCategory")
	.summary("mcp-howtocook-getRecipesByCategory --category <category:水产|早餐|调料|甜品|饮品|荤菜|半成品加工|汤|主食|素菜> [--raw <json>]")
	.description("根据分类查询菜谱，可选分类有: 水产, 早餐, 调料, 甜品, 饮品, 荤菜, 半成品加工, 汤, 主食, 素菜")
	.usage("--category <category:水产|早餐|调料|甜品|饮品|荤菜|半成品加工|汤|主食|素菜> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--category <category:水产|早餐|调料|甜品|饮品|荤菜|半成品加工|汤|主食|素菜>", "菜谱分类名称，如水产、早餐、荤菜、主食等 (choices: 水产, 早餐, 调料, 甜品, 饮品, 荤菜, 半成品加工, 汤, 主食, 素菜; example: 水产)")
	
	.alias("mcp_howtocook_getRecipesByCategory")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.category !== undefined) args.category = cmdOpts.category;
			const call = (proxy.mcpHowtocookGetRecipesByCategory as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call howtocook-mcp.mcp_howtocook_getRecipesByCategory(category: \"水产\")");

program
	.command("mcp-howtocook-recommendMeals")
	.summary("mcp-howtocook-recommendMeals [--allergies <allergies:value1,value2>] [--avoid-items <avoid-items:value1,value2>] --people-count <people-count:number> [--raw <json>]")
	.description("根据用户的忌口、过敏原、人数智能推荐菜谱，创建一周的膳食计划以及大致的购物清单")
	.usage("[--allergies <allergies:value1,value2>] [--avoid-items <avoid-items:value1,value2>] --people-count <people-count:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--allergies <allergies:value1,value2>", "过敏原列表，如[\"大蒜\", \"虾\"] (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.option("--avoid-items <avoid-items:value1,value2>", "忌口食材列表，如[\"葱\", \"姜\"] (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.requiredOption("--people-count <people-count:number>", "用餐人数，1-10之间的整数 (example: 1)", (value) => parseFloat(value))
	
	.alias("mcp_howtocook_recommendMeals")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.allergies !== undefined) args.allergies = cmdOpts.allergies;
		if (cmdOpts.avoidItems !== undefined) args.avoidItems = cmdOpts.avoidItems;
		if (cmdOpts.peopleCount !== undefined) args.peopleCount = cmdOpts.peopleCount;
			const call = (proxy.mcpHowtocookRecommendMeals as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call howtocook-mcp.mcp_howtocook_recommendMeals(allergies: [\"valu, ...)");

program
	.command("mcp-howtocook-whatToEat")
	.summary("mcp-howtocook-whatToEat --people-count <people-count:number> [--raw <json>]")
	.description("不知道吃什么？根据人数直接推荐适合的菜品组合")
	.usage("--people-count <people-count:number> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--people-count <people-count:number>", "用餐人数，1-10之间的整数，会根据人数推荐合适数量的菜品 (example: 1)", (value) => parseFloat(value))
	
	.alias("mcp_howtocook_whatToEat")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.peopleCount !== undefined) args.peopleCount = cmdOpts.peopleCount;
			const call = (proxy.mcpHowtocookWhatToEat as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call howtocook-mcp.mcp_howtocook_whatToEat(peopleCount: 1)");

program
	.command("mcp-howtocook-getRecipeById")
	.summary("mcp-howtocook-getRecipeById --query <query> [--raw <json>]")
	.description("根据菜谱名称或ID查询指定菜谱的完整详情，包括食材、步骤等")
	.usage("--query <query> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "菜谱名称或ID，支持模糊匹配菜谱名称")
	
	.alias("mcp_howtocook_getRecipeById")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
			const call = (proxy.mcpHowtocookGetRecipeById as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call howtocook-mcp.mcp_howtocook_getRecipeById(query: \"value\")");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
